# Generated by Django 5.0.1 on 2024-01-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0002_commissionpayment_salarypayment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionpayment",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2, help_text="example 0.05 = 5%", max_digits=5
            ),
        ),
    ]
