# Generated by Django 5.0.1 on 2024-01-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0003_alter_commissionpayment_commission_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="monthly_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, max_length=255, null=True
            ),
        ),
    ]
